---
project_name: zamaneh

release:
  github:
    owner: 1995parham
    name: zamaneh

builds:
  - binary: zamaneh
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w
      - -X github.com/1995parham/zamaneh/cmd.Version={{.Version}}
      - -X github.com/1995parham/zamaneh/cmd.Commit={{.Commit}}
      - -X github.com/1995parham/zamaneh/cmd.Date={{.Date}}
      - -X github.com/1995parham/zamaneh/cmd.BuiltBy=goreleaser

archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
brews:
  - name: zamaneh
    tap:
      owner: 1995parham
      name: homebrew-tap
    description: "Manage your working periods with ease"
