[package]
name = "zamaneh"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
termion = "4.0.2"
tokio = { version = "1.42", features = ["full"] }
