---
name: ci
on:
  push:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v5

      - name: run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: run cargo clippy
        run: |
          cargo clippy -- -D warnings

      - run: |
          cargo test
